import { type MonacoLanguage } from './monacoLanguages';

export const monacoLanguageLabels: Record<MonacoLanguage, string> = {
    'plaintext': 'Plain Text',
    'abap': 'ABAP',
    'apex': 'Apex',
    'azcli': 'Azure CLI',
    'bat': 'Batch',
    'bicep': 'Bicep',
    'cameligo': 'CameLIGO',
    'clojure': 'Clojure',
    'coffeescript': 'CoffeeScript',
    'c': 'C',
    'cpp': 'C++',
    'csharp': 'C#',
    'csp': 'CSP',
    'css': 'CSS',
    'cypher': 'Cypher',
    'dart': 'Dart',
    'dockerfile': 'Dockerfile',
    'ecl': 'ECL',
    'elixir': 'Elixir',
    'flow9': 'Flow9',
    'fsharp': 'F#',
    'freemarker2': 'FreeMarker',
    'freemarker2.tag-angle.interpolation-dollar': 'FreeMarker (Angle/Dollar)',
    'freemarker2.tag-bracket.interpolation-dollar': 'FreeMarker (Bracket/Dollar)',
    'freemarker2.tag-angle.interpolation-bracket': 'FreeMarker (Angle/Bracket)',
    'freemarker2.tag-bracket.interpolation-bracket': 'FreeMarker (Bracket/Bracket)',
    'freemarker2.tag-auto.interpolation-dollar': 'FreeMarker (Auto/Dollar)',
    'freemarker2.tag-auto.interpolation-bracket': 'FreeMarker (Auto/Bracket)',
    'go': 'Go',
    'graphql': 'GraphQL',
    'handlebars': 'Handlebars',
    'hcl': 'HCL',
    'html': 'HTML',
    'ini': 'INI',
    'java': 'Java',
    'javascript': 'JavaScript',
    'julia': 'Julia',
    'kotlin': 'Kotlin',
    'less': 'Less',
    'lexon': 'Lexon',
    'lua': 'Lua',
    'liquid': 'Liquid',
    'm3': 'Modula-3',
    'markdown': 'Markdown',
    'mdx': 'MDX',
    'mips': 'MIPS Assembly',
    'msdax': 'MS DAX',
    'mysql': 'MySQL',
    'objective-c': 'Objective-C',
    'pascal': 'Pascal',
    'pascaligo': 'PascaLIGO',
    'perl': 'Perl',
    'pgsql': 'PostgreSQL',
    'php': 'PHP',
    'pla': 'PLA',
    'postiats': 'ATS/Postiats',
    'powerquery': 'Power Query M',
    'powershell': 'PowerShell',
    'proto': 'Protocol Buffers',
    'pug': 'Pug',
    'python': 'Python',
    'qsharp': 'Q#',
    'r': 'R',
    'razor': 'Razor',
    'redis': 'Redis',
    'redshift': 'Amazon Redshift',
    'restructuredtext': 'reStructuredText',
    'ruby': 'Ruby',
    'rust': 'Rust',
    'sb': 'Small Basic',
    'scala': 'Scala',
    'scheme': 'Scheme',
    'scss': 'SCSS',
    'shell': 'Shell Script',
    'sol': 'Solidity',
    'aes': 'AES',
    'sparql': 'SPARQL',
    'sql': 'SQL',
    'st': 'Structured Text',
    'swift': 'Swift',
    'systemverilog': 'SystemVerilog',
    'verilog': 'Verilog',
    'tcl': 'Tcl',
    'twig': 'Twig',
    'typescript': 'TypeScript',
    'typespec': 'TypeSpec',
    'vb': 'Visual Basic',
    'wgsl': 'WebGPU Shading Language',
    'xml': 'XML',
    'yaml': 'YAML',
    'json': 'JSON'
};

export const getLanguageLabel = (language: MonacoLanguage): string => {
    return monacoLanguageLabels[language] || language;
};